[package]
name = "kasitek-tenants"
version.workspace = true
edition.workspace = true
default-run = "kasitek-tenants"

[dependencies]
actix-cors.workspace = true
actix-web.workspace = true
analytics-producer.workspace = true
analytics-reporting.workspace = true
bcrypt = "0.15"
chrono.workspace = true
config.workspace = true
crypto-utils.workspace = true
cuid2 = "0.1"
dotenv.workspace = true
log.workspace = true
observability.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true

[[bin]]
name = "kasitek-tenants"
path = "src/main.rs"
