[workspace]
members = ["kasitek-tenants"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
actix-cors = "0.7"
actix-web = "4"
analytics-producer = { git = "https://github.com/Kasitek-Labs/kasitek-labs.git", tag = "rust-crates-v0.1.0", version = "0.1.0" }
analytics-reporting = { git = "https://github.com/Kasitek-Labs/kasitek-labs.git", tag = "rust-crates-v0.1.0", version = "0.1.0" }
chrono = { version = "0.4", features = ["serde"] }
config = { git = "https://github.com/Kasitek-Labs/kasitek-labs.git", tag = "rust-crates-v0.1.0", version = "0.1.0" }
crypto-utils = { git = "https://github.com/Kasitek-Labs/kasitek-labs.git", tag = "rust-crates-v0.1.0", version = "0.1.0" }
dotenv = "0.15"
log = "0.4"
observability = { git = "https://github.com/Kasitek-Labs/kasitek-labs.git", tag = "rust-crates-v0.1.0", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "chrono", "json"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false
